services:
  - type: web
    name: youtube-sync
    env: node
    buildCommand: cd server && npm install && cd ../client && npm install && npm run build
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080

